# After changing this file, check it on:
#   http://lint.travis-ci.org/
language: python
sudo: false

matrix:
  include:
    - python: 2.7
    - python: 3.6

install:
  - python setup.py install

script:
  pytest
